
services:
  nginx:
    build: requirements/nginx/.
    image: nginx
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - 80:80
    volumes:
      - wp-data:/var/www/html
    networks:
      - inception

  wordpress:
    build: requirements/wordpress/.
    image: wordpress
    container_name: wp-php
    depends_on:
      - mariadb
    volumes:
      - wp-data:/var/www/html
    networks:
      - inception

  mariadb:
    build: requirements/mariadb/.
    image: mariadb
    container_name: mariadb
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - inception
  
networks:
  inception:

# use the local filesystem on the host machine to store the volume's data
volumes:
  db-data:
    driver: local
  wp-data:
    driver: local
