
services:
  nginx:
    build: requirements/nginx/.
    image: nginx
    container_name: nginx
    init: true
    depends_on:
      - wordpress
      - mariadb
    secrets:
      - site_key
      - site_cert
    ports:
      - 443:443
    volumes:
      - wp-data:/var/www/html
    networks:
      - inception

  wordpress:
    build: requirements/wordpress/.
    image: wordpress
    container_name: wp-php
    init: true
    depends_on:
      - mariadb
    volumes:
      - wp-data:/var/www/html
    networks:
      - inception

  mariadb:
    build: requirements/mariadb/.
    image: mariadb
    container_name: mariadb
    init: true
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - inception
  
networks:
  inception:

# use the local filesystem on the host machine to store the volume's data
volumes:
  db-data:
    driver: local
  wp-data:
    driver: local

secrets:
  site_key:
    file: ../.secrets/site.key
  site_cert:
    file: ../.secrets/site.crt
